name: WordPress Plugin Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present

    
  plugin-check:
    needs: build-plugin
    
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Run plugin check
          uses: wordpress/plugin-check-action@v1
